Book crud operations
wolox-training/jt-java pull request #4
Opened 2021-01-07 20:10 UTC by tobon96

## Summary
- Created a controller to implement all CRUD operations over Book entity
- Configured an ExceptionsHandler to create custom responses for each exception
## Trello Cards
- https://trello.com/c/js3YgJU6/18-crear-las-operaciones-crud-de-book

2021-01-08 14:41 UTC, jeymarsonwolox submitted a review, later dismissed

2021-01-11 17:40 UTC, rabinovichm requested changes
Nice work! Just one tiny fix and you are ready to go

2021-01-11 17:40 UTC, rabinovichm commented on src/main/java/wolox/training/controllers/BookController.java
> +        if(!bookRepository.existsById(id)) {
I would throw the IdMismatchException first, so if this happens, you will avoid getting to the database to check if there's a book with the provided id, which will be useless at the end. (Principle of [fail fast](https://en.wikipedia.org/wiki/Fail-fast) 🤓 )
Also, by making this change, if the IdMismatchException is not thrown, you can be sure that you are actually looking for the right id on the DB. I mean, as it is right now, when you check existence, you cannot be sure that `id` and `book.id` are equal, so why are you only checking the existence using the param `id` and not by `book.id`. (I posted my trail of thoughts just so you could understand my suggestion, it's not wrong but you did, but you could improve it 💪 )

2021-01-11 17:40 UTC, rabinovichm commented on src/main/java/wolox/training/exceptions/ExceptionsResponse.java
> +	private String error;
As a convention, we always declare all attributes at the top of the class, even before constructors 😋

2021-01-11 17:40 UTC, rabinovichm commented on src/main/java/wolox/training/models/Book.java
> +	@NotNull(message = "Book author cannot be null")
I love that you added an error message 👏

2021-01-12 14:10 UTC, rabinovichm approved these changes

2021-01-12 18:56 UTC, jeymarsonwolox approved these changes

2021-01-12 18:58 UTC, merged